### ISSUE TITLE
Write READEME.md, to show how to set up dev env

### ISSUE THREAD

**Issue by grahamjenson** [grahamjenson/plast#1]

**Comment by acbramley** [comment]
I followed this tuturial http://my-ideas-lab.net/myBlog/2012/12/setting-up-ruby-on-rails-via-rvm-on-ubuntu/

I also needed to sudo apt-get install nodejs before `rails s`

I then used http://guides.rubyonrails.org/getting_started.html section 3.3 to create my database.yml and ran rake db:create and rake db:migrate then restarted the rails server (CTRL+C then rails s)

DONE!
